---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vector-search-service
  namespace: servicenow-ai-poc
  labels:
    app: vector-search-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: vector-search-service:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vector-search-service
  namespace: servicenow-ai-poc
  labels:
    app: vector-search-service
spec:
  lookupPolicy:
    local: true
