apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: servicenow-ai-poc

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - networkpolicy.yaml

images:
  - name: vector-search-service
    newName: vector-search-service
    newTag: latest

labels:
  - pairs:
      app: vector-search-service
      version: v1

replicas:
  - name: vector-search-service
    count: 1
