apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vector-search-service
  namespace: servicenow-ai-poc
spec:
  to:
    kind: Service
    name: vector-search-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
